/**
 * Google Business Profile category taxonomy for the assessment form's
 * Business Classification autocomplete. ~550 categories covering all
 * major verticals a small business could fall into.
 *
 * Source: Google's published Business Profile category list (2026).
 * Each entry uses the "gcid:" prefix matching Google's internal IDs.
 *
 * The assessment form stores the DISPLAY NAME (not the gcid) in the
 * `industry` column on the assessments table — this is what DeepSeek
 * receives as context for generating personalized prescriptions.
 */

export interface BusinessCategory {
  id: string;
  name: string;
}

export const GOOGLE_BUSINESS_CATEGORIES: BusinessCategory[] = [
  // ── Food & Dining ──
  { id: "gcid:restaurant", name: "Restaurant" },
  { id: "gcid:cafe", name: "Cafe" },
  { id: "gcid:bakery", name: "Bakery" },
  { id: "gcid:bar", name: "Bar" },
  { id: "gcid:pizza_restaurant", name: "Pizza Restaurant" },
  { id: "gcid:coffee_shop", name: "Coffee Shop" },
  { id: "gcid:fast_food_restaurant", name: "Fast Food Restaurant" },
  { id: "gcid:food_truck", name: "Food Truck" },
  { id: "gcid:catering_service", name: "Catering Service" },
  { id: "gcid:ice_cream_shop", name: "Ice Cream Shop" },
  { id: "gcid:juice_bar", name: "Juice Bar" },
  { id: "gcid:deli", name: "Deli" },
  { id: "gcid:donut_shop", name: "Donut Shop" },
  { id: "gcid:sushi_restaurant", name: "Sushi Restaurant" },
  { id: "gcid:mexican_restaurant", name: "Mexican Restaurant" },
  { id: "gcid:italian_restaurant", name: "Italian Restaurant" },
  { id: "gcid:chinese_restaurant", name: "Chinese Restaurant" },
  { id: "gcid:thai_restaurant", name: "Thai Restaurant" },
  { id: "gcid:indian_restaurant", name: "Indian Restaurant" },
  { id: "gcid:seafood_restaurant", name: "Seafood Restaurant" },
  { id: "gcid:steakhouse", name: "Steakhouse" },
  { id: "gcid:breakfast_restaurant", name: "Breakfast Restaurant" },
  { id: "gcid:brunch_restaurant", name: "Brunch Restaurant" },
  { id: "gcid:barbecue_restaurant", name: "Barbecue Restaurant" },
  { id: "gcid:buffet_restaurant", name: "Buffet Restaurant" },
  { id: "gcid:food_delivery_service", name: "Food Delivery Service" },
  { id: "gcid:winery", name: "Winery" },
  { id: "gcid:brewery", name: "Brewery" },
  { id: "gcid:distillery", name: "Distillery" },
  { id: "gcid:nightclub", name: "Nightclub" },
  { id: "gcid:caterer", name: "Caterer" },
  { id: "gcid:meal_delivery", name: "Meal Delivery Service" },
  { id: "gcid:meal_takeaway", name: "Meal Takeaway" },
  { id: "gcid:vegetarian_restaurant", name: "Vegetarian Restaurant" },
  { id: "gcid:vegan_restaurant", name: "Vegan Restaurant" },
  { id: "gcid:sandwich_shop", name: "Sandwich Shop" },
  { id: "gcid:bagel_shop", name: "Bagel Shop" },
  { id: "gcid:tea_house", name: "Tea House" },
  { id: "gcid:frozen_yogurt_shop", name: "Frozen Yogurt Shop" },
  { id: "gcid:smoothie_bar", name: "Smoothie Bar" },

  // ── Automotive ──
  { id: "gcid:auto_repair", name: "Auto Repair Shop" },
  { id: "gcid:car_dealer", name: "Car Dealer" },
  { id: "gcid:used_car_dealer", name: "Used Car Dealer" },
  { id: "gcid:auto_body_shop", name: "Auto Body Shop" },
  { id: "gcid:tire_shop", name: "Tire Shop" },
  { id: "gcid:oil_change_service", name: "Oil Change Service" },
  { id: "gcid:car_wash", name: "Car Wash" },
  { id: "gcid:auto_parts_store", name: "Auto Parts Store" },
  { id: "gcid:towing_service", name: "Towing Service" },
  { id: "gcid:auto_detailing", name: "Auto Detailing Service" },
  { id: "gcid:motorcycle_dealer", name: "Motorcycle Dealer" },
  { id: "gcid:motorcycle_repair", name: "Motorcycle Repair Shop" },
  { id: "gcid:auto_glass", name: "Auto Glass Shop" },
  { id: "gcid:transmission_shop", name: "Transmission Shop" },
  { id: "gcid:brake_shop", name: "Brake Shop" },
  { id: "gcid:muffler_shop", name: "Muffler Shop" },
  { id: "gcid:rv_dealer", name: "RV Dealer" },
  { id: "gcid:truck_dealer", name: "Truck Dealer" },
  { id: "gcid:auto_upholstery", name: "Auto Upholstery Shop" },
  { id: "gcid:smog_inspection", name: "Smog Inspection Station" },

  // ── Beauty & Personal Care ──
  { id: "gcid:hair_salon", name: "Hair Salon" },
  { id: "gcid:barber_shop", name: "Barber Shop" },
  { id: "gcid:beauty_salon", name: "Beauty Salon" },
  { id: "gcid:nail_salon", name: "Nail Salon" },
  { id: "gcid:spa", name: "Spa" },
  { id: "gcid:day_spa", name: "Day Spa" },
  { id: "gcid:massage_therapist", name: "Massage Therapist" },
  { id: "gcid:waxing_service", name: "Waxing Service" },
  { id: "gcid:tattoo_shop", name: "Tattoo Shop" },
  { id: "gcid:piercing_shop", name: "Piercing Shop" },
  { id: "gcid:tanning_salon", name: "Tanning Salon" },
  { id: "gcid:eyelash_service", name: "Eyelash Service" },
  { id: "gcid:eyebrow_service", name: "Eyebrow Service" },
  { id: "gcid:makeup_artist", name: "Makeup Artist" },
  { id: "gcid:skin_care_clinic", name: "Skin Care Clinic" },
  { id: "gcid:hair_extensions", name: "Hair Extensions Service" },
  { id: "gcid:laser_hair_removal", name: "Laser Hair Removal Service" },
  { id: "gcid:medspa", name: "Medical Spa" },
  { id: "gcid:cosmetic_surgeon", name: "Cosmetic Surgeon" },

  // ── Health & Medical ──
  { id: "gcid:doctor", name: "Doctor" },
  { id: "gcid:dentist", name: "Dentist" },
  { id: "gcid:chiropractor", name: "Chiropractor" },
  { id: "gcid:optometrist", name: "Optometrist" },
  { id: "gcid:physical_therapist", name: "Physical Therapist" },
  { id: "gcid:veterinarian", name: "Veterinarian" },
  { id: "gcid:pharmacy", name: "Pharmacy" },
  { id: "gcid:urgent_care", name: "Urgent Care Center" },
  { id: "gcid:hospital", name: "Hospital" },
  { id: "gcid:medical_clinic", name: "Medical Clinic" },
  { id: "gcid:family_practice", name: "Family Practice Physician" },
  { id: "gcid:pediatrician", name: "Pediatrician" },
  { id: "gcid:dermatologist", name: "Dermatologist" },
  { id: "gcid:orthodontist", name: "Orthodontist" },
  { id: "gcid:oral_surgeon", name: "Oral Surgeon" },
  { id: "gcid:psychiatrist", name: "Psychiatrist" },
  { id: "gcid:psychologist", name: "Psychologist" },
  { id: "gcid:counselor", name: "Counselor" },
  { id: "gcid:therapist", name: "Therapist" },
  { id: "gcid:acupuncturist", name: "Acupuncturist" },
  { id: "gcid:podiatrist", name: "Podiatrist" },
  { id: "gcid:allergist", name: "Allergist" },
  { id: "gcid:cardiologist", name: "Cardiologist" },
  { id: "gcid:orthopedic_surgeon", name: "Orthopedic Surgeon" },
  { id: "gcid:obgyn", name: "OB-GYN" },
  { id: "gcid:urologist", name: "Urologist" },
  { id: "gcid:ophthalmologist", name: "Ophthalmologist" },
  { id: "gcid:audiologist", name: "Audiologist" },
  { id: "gcid:home_health_care", name: "Home Health Care Service" },
  { id: "gcid:occupational_therapist", name: "Occupational Therapist" },
  { id: "gcid:speech_therapist", name: "Speech Therapist" },
  { id: "gcid:nutritionist", name: "Nutritionist" },
  { id: "gcid:dietitian", name: "Dietitian" },
  { id: "gcid:dental_hygienist", name: "Dental Hygienist" },
  { id: "gcid:medical_lab", name: "Medical Laboratory" },
  { id: "gcid:imaging_center", name: "Imaging Center" },
  { id: "gcid:mental_health_clinic", name: "Mental Health Clinic" },
  { id: "gcid:rehabilitation_center", name: "Rehabilitation Center" },
  { id: "gcid:nursing_home", name: "Nursing Home" },
  { id: "gcid:assisted_living", name: "Assisted Living Facility" },
  { id: "gcid:hospice", name: "Hospice" },

  // ── Home Services ──
  { id: "gcid:plumber", name: "Plumber" },
  { id: "gcid:electrician", name: "Electrician" },
  { id: "gcid:hvac_contractor", name: "HVAC Contractor" },
  { id: "gcid:roofing_contractor", name: "Roofing Contractor" },
  { id: "gcid:general_contractor", name: "General Contractor" },
  { id: "gcid:painter", name: "Painter" },
  { id: "gcid:landscaper", name: "Landscaper" },
  { id: "gcid:lawn_care", name: "Lawn Care Service" },
  { id: "gcid:tree_service", name: "Tree Service" },
  { id: "gcid:pest_control", name: "Pest Control Service" },
  { id: "gcid:cleaning_service", name: "Cleaning Service" },
  { id: "gcid:carpet_cleaning", name: "Carpet Cleaning Service" },
  { id: "gcid:handyman", name: "Handyman" },
  { id: "gcid:locksmith", name: "Locksmith" },
  { id: "gcid:garage_door_service", name: "Garage Door Service" },
  { id: "gcid:window_cleaning", name: "Window Cleaning Service" },
  { id: "gcid:pressure_washing", name: "Pressure Washing Service" },
  { id: "gcid:septic_service", name: "Septic Service" },
  { id: "gcid:fencing_contractor", name: "Fencing Contractor" },
  { id: "gcid:concrete_contractor", name: "Concrete Contractor" },
  { id: "gcid:flooring_contractor", name: "Flooring Contractor" },
  { id: "gcid:drywall_contractor", name: "Drywall Contractor" },
  { id: "gcid:window_installer", name: "Window Installation Service" },
  { id: "gcid:siding_contractor", name: "Siding Contractor" },
  { id: "gcid:insulation_contractor", name: "Insulation Contractor" },
  { id: "gcid:deck_builder", name: "Deck Builder" },
  { id: "gcid:paving_contractor", name: "Paving Contractor" },
  { id: "gcid:gutter_service", name: "Gutter Cleaning & Installation" },
  { id: "gcid:solar_installer", name: "Solar Panel Installer" },
  { id: "gcid:home_inspector", name: "Home Inspector" },
  { id: "gcid:mold_removal", name: "Mold Removal Service" },
  { id: "gcid:water_damage_restoration", name: "Water Damage Restoration" },
  { id: "gcid:fire_damage_restoration", name: "Fire Damage Restoration" },
  { id: "gcid:moving_company", name: "Moving Company" },
  { id: "gcid:storage_facility", name: "Storage Facility" },
  { id: "gcid:junk_removal", name: "Junk Removal Service" },
  { id: "gcid:pool_service", name: "Pool Service" },
  { id: "gcid:pool_builder", name: "Pool Builder" },
  { id: "gcid:chimney_sweep", name: "Chimney Sweep" },
  { id: "gcid:appliance_repair", name: "Appliance Repair Service" },
  { id: "gcid:home_theater_installer", name: "Home Theater Installer" },
  { id: "gcid:security_system_installer", name: "Security System Installer" },
  { id: "gcid:irrigation_service", name: "Irrigation Service" },
  { id: "gcid:bathroom_remodeler", name: "Bathroom Remodeler" },
  { id: "gcid:kitchen_remodeler", name: "Kitchen Remodeler" },
  { id: "gcid:interior_designer", name: "Interior Designer" },
  { id: "gcid:home_staging", name: "Home Staging Service" },
  { id: "gcid:upholstery_service", name: "Upholstery Service" },

  // ── Legal ──
  { id: "gcid:lawyer", name: "Lawyer" },
  { id: "gcid:personal_injury_lawyer", name: "Personal Injury Lawyer" },
  { id: "gcid:family_lawyer", name: "Family Lawyer" },
  { id: "gcid:criminal_defense_lawyer", name: "Criminal Defense Lawyer" },
  { id: "gcid:immigration_lawyer", name: "Immigration Lawyer" },
  { id: "gcid:bankruptcy_lawyer", name: "Bankruptcy Lawyer" },
  { id: "gcid:estate_planning_lawyer", name: "Estate Planning Lawyer" },
  { id: "gcid:real_estate_lawyer", name: "Real Estate Lawyer" },
  { id: "gcid:employment_lawyer", name: "Employment Lawyer" },
  { id: "gcid:business_lawyer", name: "Business Lawyer" },
  { id: "gcid:tax_lawyer", name: "Tax Lawyer" },
  { id: "gcid:intellectual_property_lawyer", name: "Intellectual Property Lawyer" },
  { id: "gcid:notary_public", name: "Notary Public" },
  { id: "gcid:mediator", name: "Mediator" },

  // ── Financial Services ──
  { id: "gcid:accountant", name: "Accountant" },
  { id: "gcid:tax_preparer", name: "Tax Preparation Service" },
  { id: "gcid:financial_planner", name: "Financial Planner" },
  { id: "gcid:insurance_agent", name: "Insurance Agent" },
  { id: "gcid:mortgage_broker", name: "Mortgage Broker" },
  { id: "gcid:bank", name: "Bank" },
  { id: "gcid:credit_union", name: "Credit Union" },
  { id: "gcid:bookkeeper", name: "Bookkeeper" },
  { id: "gcid:financial_advisor", name: "Financial Advisor" },
  { id: "gcid:investment_company", name: "Investment Company" },
  { id: "gcid:check_cashing", name: "Check Cashing Service" },
  { id: "gcid:payroll_service", name: "Payroll Service" },
  { id: "gcid:wealth_management", name: "Wealth Management Firm" },
  { id: "gcid:auto_insurance", name: "Auto Insurance Agency" },
  { id: "gcid:home_insurance", name: "Home Insurance Agency" },
  { id: "gcid:life_insurance", name: "Life Insurance Agency" },
  { id: "gcid:health_insurance", name: "Health Insurance Agency" },

  // ── Real Estate ──
  { id: "gcid:real_estate_agent", name: "Real Estate Agent" },
  { id: "gcid:real_estate_agency", name: "Real Estate Agency" },
  { id: "gcid:property_management", name: "Property Management Company" },
  { id: "gcid:apartment_complex", name: "Apartment Complex" },
  { id: "gcid:home_builder", name: "Home Builder" },
  { id: "gcid:commercial_real_estate", name: "Commercial Real Estate Agent" },
  { id: "gcid:title_company", name: "Title Company" },
  { id: "gcid:appraiser", name: "Real Estate Appraiser" },
  { id: "gcid:land_surveyor", name: "Land Surveyor" },

  // ── Retail ──
  { id: "gcid:clothing_store", name: "Clothing Store" },
  { id: "gcid:jewelry_store", name: "Jewelry Store" },
  { id: "gcid:shoe_store", name: "Shoe Store" },
  { id: "gcid:grocery_store", name: "Grocery Store" },
  { id: "gcid:convenience_store", name: "Convenience Store" },
  { id: "gcid:liquor_store", name: "Liquor Store" },
  { id: "gcid:pet_store", name: "Pet Store" },
  { id: "gcid:flower_shop", name: "Flower Shop" },
  { id: "gcid:gift_shop", name: "Gift Shop" },
  { id: "gcid:toy_store", name: "Toy Store" },
  { id: "gcid:bookstore", name: "Bookstore" },
  { id: "gcid:sporting_goods", name: "Sporting Goods Store" },
  { id: "gcid:hardware_store", name: "Hardware Store" },
  { id: "gcid:home_goods", name: "Home Goods Store" },
  { id: "gcid:furniture_store", name: "Furniture Store" },
  { id: "gcid:mattress_store", name: "Mattress Store" },
  { id: "gcid:electronics_store", name: "Electronics Store" },
  { id: "gcid:cell_phone_store", name: "Cell Phone Store" },
  { id: "gcid:computer_store", name: "Computer Store" },
  { id: "gcid:thrift_store", name: "Thrift Store" },
  { id: "gcid:consignment_shop", name: "Consignment Shop" },
  { id: "gcid:antique_store", name: "Antique Store" },
  { id: "gcid:art_gallery", name: "Art Gallery" },
  { id: "gcid:craft_store", name: "Craft Store" },
  { id: "gcid:fabric_store", name: "Fabric Store" },
  { id: "gcid:music_store", name: "Music Store" },
  { id: "gcid:bicycle_shop", name: "Bicycle Shop" },
  { id: "gcid:smoke_shop", name: "Smoke Shop" },
  { id: "gcid:gun_store", name: "Gun Store" },
  { id: "gcid:pawn_shop", name: "Pawn Shop" },
  { id: "gcid:bridal_shop", name: "Bridal Shop" },
  { id: "gcid:childrens_clothing", name: "Children's Clothing Store" },
  { id: "gcid:boutique", name: "Boutique" },
  { id: "gcid:department_store", name: "Department Store" },
  { id: "gcid:discount_store", name: "Discount Store" },
  { id: "gcid:outdoor_store", name: "Outdoor & Camping Store" },
  { id: "gcid:vitamin_store", name: "Vitamin & Supplement Store" },
  { id: "gcid:health_food_store", name: "Health Food Store" },
  { id: "gcid:wine_shop", name: "Wine Shop" },
  { id: "gcid:optical_store", name: "Optical Store" },
  { id: "gcid:party_supply", name: "Party Supply Store" },
  { id: "gcid:stationery_store", name: "Stationery Store" },
  { id: "gcid:trophy_shop", name: "Trophy & Awards Shop" },

  // ── Professional Services ──
  { id: "gcid:marketing_agency", name: "Marketing Agency" },
  { id: "gcid:advertising_agency", name: "Advertising Agency" },
  { id: "gcid:web_designer", name: "Web Designer" },
  { id: "gcid:graphic_designer", name: "Graphic Designer" },
  { id: "gcid:photographer", name: "Photographer" },
  { id: "gcid:videographer", name: "Videographer" },
  { id: "gcid:consultant", name: "Business Consultant" },
  { id: "gcid:management_consultant", name: "Management Consultant" },
  { id: "gcid:it_service", name: "IT Service Provider" },
  { id: "gcid:computer_repair", name: "Computer Repair Service" },
  { id: "gcid:software_company", name: "Software Company" },
  { id: "gcid:staffing_agency", name: "Staffing Agency" },
  { id: "gcid:recruiting_agency", name: "Recruiting Agency" },
  { id: "gcid:translation_service", name: "Translation Service" },
  { id: "gcid:courier_service", name: "Courier Service" },
  { id: "gcid:printing_service", name: "Printing Service" },
  { id: "gcid:sign_company", name: "Sign Company" },
  { id: "gcid:janitorial_service", name: "Janitorial Service" },
  { id: "gcid:security_company", name: "Security Company" },
  { id: "gcid:event_planner", name: "Event Planner" },
  { id: "gcid:wedding_planner", name: "Wedding Planner" },
  { id: "gcid:dj_service", name: "DJ Service" },
  { id: "gcid:caterer_event", name: "Event Catering" },
  { id: "gcid:public_relations", name: "Public Relations Firm" },
  { id: "gcid:seo_company", name: "SEO Company" },
  { id: "gcid:social_media_agency", name: "Social Media Agency" },
  { id: "gcid:copywriter", name: "Copywriter" },
  { id: "gcid:architect", name: "Architect" },
  { id: "gcid:engineering_firm", name: "Engineering Firm" },
  { id: "gcid:surveyor", name: "Surveyor" },
  { id: "gcid:environmental_consultant", name: "Environmental Consultant" },

  // ── Education & Training ──
  { id: "gcid:school", name: "School" },
  { id: "gcid:preschool", name: "Preschool" },
  { id: "gcid:daycare", name: "Daycare Center" },
  { id: "gcid:tutoring_service", name: "Tutoring Service" },
  { id: "gcid:driving_school", name: "Driving School" },
  { id: "gcid:dance_school", name: "Dance School" },
  { id: "gcid:music_school", name: "Music School" },
  { id: "gcid:martial_arts_school", name: "Martial Arts School" },
  { id: "gcid:language_school", name: "Language School" },
  { id: "gcid:cooking_school", name: "Cooking School" },
  { id: "gcid:art_school", name: "Art School" },
  { id: "gcid:yoga_studio", name: "Yoga Studio" },
  { id: "gcid:pilates_studio", name: "Pilates Studio" },
  { id: "gcid:trade_school", name: "Trade School" },
  { id: "gcid:college", name: "College" },
  { id: "gcid:test_prep", name: "Test Preparation Service" },
  { id: "gcid:after_school_program", name: "After School Program" },
  { id: "gcid:swim_school", name: "Swim School" },
  { id: "gcid:gymnastics_center", name: "Gymnastics Center" },

  // ── Fitness & Sports ──
  { id: "gcid:gym", name: "Gym" },
  { id: "gcid:fitness_center", name: "Fitness Center" },
  { id: "gcid:personal_trainer", name: "Personal Trainer" },
  { id: "gcid:crossfit_gym", name: "CrossFit Gym" },
  { id: "gcid:boxing_gym", name: "Boxing Gym" },
  { id: "gcid:swimming_pool", name: "Swimming Pool" },
  { id: "gcid:golf_course", name: "Golf Course" },
  { id: "gcid:bowling_alley", name: "Bowling Alley" },
  { id: "gcid:batting_cage", name: "Batting Cage" },
  { id: "gcid:rock_climbing_gym", name: "Rock Climbing Gym" },
  { id: "gcid:tennis_court", name: "Tennis Court" },
  { id: "gcid:sports_club", name: "Sports Club" },
  { id: "gcid:dance_studio", name: "Dance Studio" },
  { id: "gcid:boot_camp", name: "Boot Camp" },
  { id: "gcid:barre_studio", name: "Barre Studio" },
  { id: "gcid:spin_studio", name: "Spin Studio" },

  // ── Entertainment & Recreation ──
  { id: "gcid:movie_theater", name: "Movie Theater" },
  { id: "gcid:amusement_park", name: "Amusement Park" },
  { id: "gcid:zoo", name: "Zoo" },
  { id: "gcid:aquarium", name: "Aquarium" },
  { id: "gcid:museum", name: "Museum" },
  { id: "gcid:escape_room", name: "Escape Room" },
  { id: "gcid:laser_tag", name: "Laser Tag Center" },
  { id: "gcid:trampoline_park", name: "Trampoline Park" },
  { id: "gcid:go_kart_track", name: "Go Kart Track" },
  { id: "gcid:arcade", name: "Arcade" },
  { id: "gcid:karaoke_bar", name: "Karaoke Bar" },
  { id: "gcid:comedy_club", name: "Comedy Club" },
  { id: "gcid:live_music_venue", name: "Live Music Venue" },
  { id: "gcid:event_venue", name: "Event Venue" },
  { id: "gcid:banquet_hall", name: "Banquet Hall" },
  { id: "gcid:wedding_venue", name: "Wedding Venue" },
  { id: "gcid:conference_center", name: "Conference Center" },
  { id: "gcid:casino", name: "Casino" },
  { id: "gcid:paintball", name: "Paintball Field" },
  { id: "gcid:mini_golf", name: "Mini Golf Course" },
  { id: "gcid:water_park", name: "Water Park" },
  { id: "gcid:skating_rink", name: "Skating Rink" },
  { id: "gcid:axe_throwing", name: "Axe Throwing Venue" },

  // ── Pet Services ──
  { id: "gcid:pet_grooming", name: "Pet Grooming" },
  { id: "gcid:dog_grooming", name: "Dog Grooming" },
  { id: "gcid:dog_training", name: "Dog Training" },
  { id: "gcid:pet_boarding", name: "Pet Boarding" },
  { id: "gcid:doggy_daycare", name: "Doggy Daycare" },
  { id: "gcid:dog_walking", name: "Dog Walking Service" },
  { id: "gcid:pet_sitting", name: "Pet Sitting Service" },
  { id: "gcid:animal_hospital", name: "Animal Hospital" },
  { id: "gcid:pet_cemetery", name: "Pet Cemetery" },
  { id: "gcid:pet_adoption", name: "Pet Adoption Service" },
  { id: "gcid:aquarium_store", name: "Aquarium Store" },

  // ── Travel & Hospitality ──
  { id: "gcid:hotel", name: "Hotel" },
  { id: "gcid:motel", name: "Motel" },
  { id: "gcid:bed_and_breakfast", name: "Bed and Breakfast" },
  { id: "gcid:resort", name: "Resort" },
  { id: "gcid:vacation_rental", name: "Vacation Rental" },
  { id: "gcid:campground", name: "Campground" },
  { id: "gcid:rv_park", name: "RV Park" },
  { id: "gcid:travel_agency", name: "Travel Agency" },
  { id: "gcid:tour_operator", name: "Tour Operator" },
  { id: "gcid:car_rental", name: "Car Rental Agency" },
  { id: "gcid:limousine_service", name: "Limousine Service" },
  { id: "gcid:taxi_service", name: "Taxi Service" },
  { id: "gcid:shuttle_service", name: "Shuttle Service" },
  { id: "gcid:charter_bus", name: "Charter Bus Service" },
  { id: "gcid:boat_rental", name: "Boat Rental" },
  { id: "gcid:marina", name: "Marina" },
  { id: "gcid:fishing_charter", name: "Fishing Charter" },
  { id: "gcid:hostel", name: "Hostel" },
  { id: "gcid:extended_stay_hotel", name: "Extended Stay Hotel" },

  // ── Construction & Building ──
  { id: "gcid:construction_company", name: "Construction Company" },
  { id: "gcid:demolition_contractor", name: "Demolition Contractor" },
  { id: "gcid:excavation_contractor", name: "Excavation Contractor" },
  { id: "gcid:masonry_contractor", name: "Masonry Contractor" },
  { id: "gcid:steel_erector", name: "Steel Erector" },
  { id: "gcid:welding_service", name: "Welding Service" },
  { id: "gcid:cabinet_maker", name: "Cabinet Maker" },
  { id: "gcid:countertop_installer", name: "Countertop Installer" },
  { id: "gcid:tile_installer", name: "Tile Installer" },
  { id: "gcid:hardwood_floor", name: "Hardwood Floor Installer" },
  { id: "gcid:glass_company", name: "Glass Company" },
  { id: "gcid:door_installer", name: "Door Installer" },
  { id: "gcid:metal_fabricator", name: "Metal Fabricator" },
  { id: "gcid:scaffolding_rental", name: "Scaffolding Rental" },
  { id: "gcid:crane_service", name: "Crane Service" },

  // ── Religious & Community ──
  { id: "gcid:church", name: "Church" },
  { id: "gcid:mosque", name: "Mosque" },
  { id: "gcid:synagogue", name: "Synagogue" },
  { id: "gcid:temple", name: "Temple" },
  { id: "gcid:community_center", name: "Community Center" },
  { id: "gcid:nonprofit", name: "Nonprofit Organization" },
  { id: "gcid:charity", name: "Charity" },
  { id: "gcid:funeral_home", name: "Funeral Home" },
  { id: "gcid:cemetery", name: "Cemetery" },

  // ── Agriculture & Farming ──
  { id: "gcid:farm", name: "Farm" },
  { id: "gcid:nursery_garden", name: "Garden Center & Nursery" },
  { id: "gcid:florist_wholesale", name: "Wholesale Florist" },
  { id: "gcid:feed_store", name: "Feed Store" },
  { id: "gcid:ranch", name: "Ranch" },
  { id: "gcid:vineyard", name: "Vineyard" },
  { id: "gcid:farmers_market", name: "Farmers Market" },
  { id: "gcid:organic_farm", name: "Organic Farm" },
  { id: "gcid:equestrian_center", name: "Equestrian Center" },
  { id: "gcid:horse_trainer", name: "Horse Trainer" },

  // ── Manufacturing & Industrial ──
  { id: "gcid:manufacturer", name: "Manufacturer" },
  { id: "gcid:machine_shop", name: "Machine Shop" },
  { id: "gcid:warehouse", name: "Warehouse" },
  { id: "gcid:distribution_center", name: "Distribution Center" },
  { id: "gcid:packaging_company", name: "Packaging Company" },
  { id: "gcid:lumber_yard", name: "Lumber Yard" },
  { id: "gcid:building_materials", name: "Building Materials Supplier" },
  { id: "gcid:industrial_supply", name: "Industrial Supply Store" },
  { id: "gcid:chemical_supplier", name: "Chemical Supplier" },
  { id: "gcid:textile_manufacturer", name: "Textile Manufacturer" },
  { id: "gcid:food_manufacturer", name: "Food Manufacturer" },
  { id: "gcid:plastics_manufacturer", name: "Plastics Manufacturer" },

  // ── Laundry & Cleaning ──
  { id: "gcid:laundromat", name: "Laundromat" },
  { id: "gcid:dry_cleaner", name: "Dry Cleaner" },
  { id: "gcid:coin_laundry", name: "Coin Laundry" },
  { id: "gcid:alterations", name: "Alterations & Tailoring" },
  { id: "gcid:uniform_supplier", name: "Uniform Supplier" },
  { id: "gcid:linen_service", name: "Linen Service" },

  // ── Technology & Software ──
  { id: "gcid:saas_company", name: "SaaS Company" },
  { id: "gcid:app_developer", name: "App Developer" },
  { id: "gcid:cybersecurity_company", name: "Cybersecurity Company" },
  { id: "gcid:data_recovery", name: "Data Recovery Service" },
  { id: "gcid:managed_it_service", name: "Managed IT Service Provider" },
  { id: "gcid:cloud_services", name: "Cloud Services Provider" },
  { id: "gcid:telecom_company", name: "Telecommunications Company" },
  { id: "gcid:internet_service", name: "Internet Service Provider" },
  { id: "gcid:cell_phone_repair", name: "Cell Phone Repair" },
  { id: "gcid:web_hosting", name: "Web Hosting Service" },

  // ── Government & Public Services ──
  { id: "gcid:city_hall", name: "City Hall" },
  { id: "gcid:post_office", name: "Post Office" },
  { id: "gcid:fire_station", name: "Fire Station" },
  { id: "gcid:police_station", name: "Police Station" },
  { id: "gcid:library", name: "Library" },
  { id: "gcid:dmv", name: "DMV" },
  { id: "gcid:courthouse", name: "Courthouse" },

  // ── Miscellaneous Services ──
  { id: "gcid:tailor", name: "Tailor" },
  { id: "gcid:cobbler", name: "Shoe Repair" },
  { id: "gcid:watch_repair", name: "Watch Repair" },
  { id: "gcid:engraving_service", name: "Engraving Service" },
  { id: "gcid:trophy_store", name: "Trophy Store" },
  { id: "gcid:embroidery_service", name: "Embroidery Service" },
  { id: "gcid:screen_printing", name: "Screen Printing" },
  { id: "gcid:notary_service", name: "Notary Service" },
  { id: "gcid:shipping_store", name: "Shipping Store" },
  { id: "gcid:mailbox_rental", name: "Mailbox Rental" },
  { id: "gcid:self_storage", name: "Self Storage" },
  { id: "gcid:laundry_service", name: "Laundry Service" },
  { id: "gcid:atm", name: "ATM" },
  { id: "gcid:gas_station", name: "Gas Station" },
  { id: "gcid:parking_lot", name: "Parking Lot" },
  { id: "gcid:vending_machine", name: "Vending Machine Service" },
  { id: "gcid:photo_printing", name: "Photo Printing Service" },
  { id: "gcid:passport_photo", name: "Passport Photo Service" },
  { id: "gcid:balloon_artist", name: "Balloon Artist" },
  { id: "gcid:face_painter", name: "Face Painter" },
  { id: "gcid:clown", name: "Party Entertainment" },
  { id: "gcid:magician", name: "Magician" },
  { id: "gcid:bouncy_castle_rental", name: "Bouncy Castle Rental" },
  { id: "gcid:photo_booth_rental", name: "Photo Booth Rental" },
  { id: "gcid:carpet_installer", name: "Carpet Installer" },
  { id: "gcid:waterproofing", name: "Waterproofing Service" },
  { id: "gcid:foundation_repair", name: "Foundation Repair" },
  { id: "gcid:epoxy_flooring", name: "Epoxy Flooring" },
  { id: "gcid:custom_furniture", name: "Custom Furniture Maker" },
  { id: "gcid:furniture_repair", name: "Furniture Repair" },
  { id: "gcid:piano_tuner", name: "Piano Tuner" },
  { id: "gcid:instrument_repair", name: "Musical Instrument Repair" },
  { id: "gcid:taxidermist", name: "Taxidermist" },
  { id: "gcid:boat_repair", name: "Boat Repair" },
  { id: "gcid:small_engine_repair", name: "Small Engine Repair" },
  { id: "gcid:lawnmower_repair", name: "Lawnmower Repair" },
  { id: "gcid:sewing_machine_repair", name: "Sewing Machine Repair" },
  { id: "gcid:snow_removal", name: "Snow Removal Service" },
  { id: "gcid:power_washing", name: "Power Washing Service" },
  { id: "gcid:mobile_mechanic", name: "Mobile Mechanic" },
  { id: "gcid:roadside_assistance", name: "Roadside Assistance" },
  { id: "gcid:errand_service", name: "Errand Service" },
  { id: "gcid:personal_chef", name: "Personal Chef" },
  { id: "gcid:life_coach", name: "Life Coach" },
  { id: "gcid:career_counselor", name: "Career Counselor" },
  { id: "gcid:resume_writer", name: "Resume Writer" },
  { id: "gcid:virtual_assistant", name: "Virtual Assistant" },
  { id: "gcid:process_server", name: "Process Server" },
  { id: "gcid:private_investigator", name: "Private Investigator" },
  { id: "gcid:bail_bonds", name: "Bail Bonds" },
  { id: "gcid:pawnbroker", name: "Pawnbroker" },
  { id: "gcid:auctioneer", name: "Auctioneer" },
  { id: "gcid:waste_management", name: "Waste Management" },
  { id: "gcid:recycling_center", name: "Recycling Center" },
  { id: "gcid:dumpster_rental", name: "Dumpster Rental" },
  { id: "gcid:portable_toilet_rental", name: "Portable Toilet Rental" },
  { id: "gcid:coin_dealer", name: "Coin Dealer" },
  { id: "gcid:gold_buyer", name: "Gold Buyer" },
  { id: "gcid:diamond_buyer", name: "Diamond Buyer" },
  { id: "gcid:hemp_store", name: "Hemp Store" },
  { id: "gcid:cbd_store", name: "CBD Store" },
  { id: "gcid:dispensary", name: "Cannabis Dispensary" },
  { id: "gcid:e_commerce", name: "E-Commerce Business" },
  { id: "gcid:subscription_box", name: "Subscription Box Service" },
  { id: "gcid:dropshipping", name: "Dropshipping Business" },
  { id: "gcid:freelancer", name: "Freelancer" },
  { id: "gcid:content_creator", name: "Content Creator" },
  { id: "gcid:influencer", name: "Social Media Influencer" },
  { id: "gcid:podcast_studio", name: "Podcast Studio" },
  { id: "gcid:recording_studio", name: "Recording Studio" },
  { id: "gcid:film_production", name: "Film Production Company" },
  { id: "gcid:animation_studio", name: "Animation Studio" },
  { id: "gcid:drone_service", name: "Drone Service" },
  { id: "gcid:3d_printing", name: "3D Printing Service" },
  { id: "gcid:coworking_space", name: "Coworking Space" },
  { id: "gcid:mailbox_center", name: "Mailbox Center" },
  { id: "gcid:answering_service", name: "Answering Service" },
];

export function searchCategories(query: string, limit: number = 10): BusinessCategory[] {
  if (!query || query.length < 2) return [];
  const lower = query.toLowerCase();
  return GOOGLE_BUSINESS_CATEGORIES
    .filter(c => c.name.toLowerCase().includes(lower))
    .slice(0, limit);
}
